const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
function environment(reduced,seed){
 let clock=0,id=0;const queue=new Map(),els={},storage=seed?{'jibun-company-v1':JSON.stringify(seed)}:{},expFrames=[];
 class El{constructor(name=''){this.name=name;this.hidden=false;this.parentElement={classList:{add(){},remove(){}}};this.style={setProperty(){}};this.children=[];this.className='';this.classList={add:(...cs)=>{this.className+=' '+cs.join(' ')},remove:(...cs)=>{this.className=this.className.split(' ').filter(x=>!cs.includes(x)).join(' ')}};this.value='';}set textContent(v){this.text=v;if(this.name==='exp')expFrames.push(String(v))}get textContent(){return this.text}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}setAttribute(){}querySelector(){return new El()}focus(){}getContext(){return null}showModal(){this.open=true}close(){this.open=false}reset(){}setCustomValidity(){}reportValidity(){}}
 const schedule=(fn,ms)=>{queue.set(++id,{at:clock+ms,fn});return id};
 const sandbox={document:{getElementById:n=>els[n]??=new El(n),createElement:()=>new El(),querySelector:()=>els.app??=new El(),querySelectorAll:()=>[],addEventListener(){}},window:{addEventListener(){},scrollTo(){}},location:{hash:''},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},matchMedia:()=>({matches:reduced}),navigator:{vibrate(){}},performance:{now:()=>clock},requestAnimationFrame:fn=>schedule(()=>fn(clock),16),setTimeout:schedule,clearTimeout:i=>queue.delete(i),FormData:class{get(){return 'normal'}},Date,Math,console,crypto:{randomUUID:()=> 'test-new'}};
 vm.createContext(sandbox);vm.runInContext(fs.readFileSync('dist/app.js','utf8'),sandbox);const run=code=>vm.runInContext(code,sandbox);
 async function flush(){for(let i=0;i<1500;i++){await Promise.resolve();if(!queue.size){await Promise.resolve();if(!queue.size)return;}const [key,t]=[...queue].sort((a,b)=>a[1].at-b[1].at)[0];queue.delete(key);clock=t.at;t.fn();}throw Error('Animation never settled');}
 async function finish(p){let done=false;Promise.resolve(p).then(()=>done=true);for(let i=0;i<20&&!done;i++){await flush();if(els['event-close']?.onclick&&!els['event-close'].hidden)els['event-close'].onclick();await Promise.resolve();}assert.ok(done,'explicit close resolves the operation');return p;}
 return{run,finish,flush,els,storage,queue,expFrames};
}
(async()=>{
 for(const reduced of [true,false]){
  const e=environment(reduced),{run,finish,flush,els}=e;
  assert.equal(run('state.tasks.length'),3);assert.equal(run('state.established'),false);els['company-input'].value='ぽんず商事';run('$("company-form").onsubmit({preventDefault(){}})');assert.equal(run('state.established'),true);
  assert.equal(run("quickDeadline('tomorrow',new Date(2026,11,31,23))"),'2027-01-01');assert.equal(run("quickDeadline('week',new Date(2026,9,5))"),'2026-10-11');assert.equal(run("parseDate('2026-02-30')"),null);assert.equal(run("deadlineInfo('2026-10-06',new Date(2026,9,5)).label"),'明日まで');
  const complete=run('complete("first1")');await flush();assert.equal(run('busy'),true);assert.equal(els.celebration.hidden,false);assert.equal(els['event-close'].hidden,false);assert.equal(els.celebration.onclick,undefined);assert.equal(run('state.completed.length'),1);assert.equal(run('state.completed[0].name'),'洗濯する');await flush();assert.equal(els.celebration.hidden,false,'results stay open without a timeout');await finish(complete);assert.equal(run('state.exp'),300);
  await finish(run('complete("first1")'));assert.equal(run('state.completed.length'),1);
  await finish(run('Promise.all([complete("first2"),complete("first3")])'));assert.equal(run('state.exp'),800);assert.equal(run('state.completed.length'),2);
  await finish(run('complete("first3")'));assert.equal(run('growth(state.exp).level'),2);assert.equal(els.exp.textContent,'100');assert.equal(els.goal.textContent,'2,000');assert.equal(run('state.sales'),1100);if(!reduced)assert.ok(e.expFrames.includes('1,000'));
  els['task-name'].value='書類を作る';const registration=run('$("task-form").onsubmit({preventDefault(){},target:{reset(){}}})');assert.equal(run('state.tasks.length'),1);assert.equal(run('state.exp'),1100);assert.equal(els['event-company'].textContent,'ぽんず商事');els['event-skip'].onclick();assert.equal(els['event-close'].hidden,false);assert.equal(els.celebration.hidden,false,'fast-forward does not dismiss');await finish(registration);assert.equal(run('busy'),false);assert.equal(els.app.inert,false);
  for(const [difficulty,title] of [['easy','受注\n決定！'],['normal','受注\n決定！'],['hard','特別案件\n受注決定！']]){const p=run(`celebrate('order','歯磨きする',300,undefined,'${difficulty}')`);assert.equal(els['celebrate-title'].textContent,title);els['event-skip'].onclick();await finish(p);assert.equal(els.celebration.hidden,true);assert.equal(e.queue.size,0);}
  await finish(run('complete("test-new")'));assert.equal(run('state.exp'),1600);assert.equal(run('state.completed.length'),4);assert.equal(run('state.completed[0].name'),'書類を作る');assert.equal(run('state.completed[0].exp'),500);assert.equal(run('state.completed[0].companyName'),'ぽんず商事');
  run('location.hash="#history";updateView()');assert.equal(els['home-screen'].hidden,true);assert.equal(els['history-screen'].hidden,false);assert.equal(els['home-bottom'].hidden,true);assert.equal(els['completed-count'].textContent,'4');assert.equal(els['completed-sales'].textContent,'1,600');assert.equal(els['history-list'].children.length,5);
  run('state.day="old";daily()');assert.equal(run('state.today'),0);assert.equal(run('state.completed.length'),4);
  const reloaded=environment(reduced,JSON.parse(e.storage['jibun-company-v1']));assert.equal(reloaded.run('state.completed.length'),4);assert.equal(reloaded.run('state.companyName'),'ぽんず商事');assert.equal(reloaded.run('state.exp'),1600);
  console.log('PASS '+(reduced?'reduced motion':'animated')+': persistent results, explicit close, fast-forward, single rewards/history, level chaining, history view/reload, daily rollover');
 }
 const legacy=environment(true,{exp:800,day:'old',today:3,sales:800,tasks:[{id:'kept',name:'メールを返す',difficulty:'normal'}]});assert.equal(legacy.run('state.exp'),800);assert.equal(legacy.run('state.legacyExp'),800);assert.equal(legacy.run('state.completed.length'),0);assert.equal(legacy.els['history-legacy'].hidden,false);assert.equal(legacy.run('state.established'),true);assert.equal(legacy.run('state.tasks[0].id'),'kept');console.log('PASS: old EXP retained with an honest history migration note');
})().catch(e=>{console.error(e);process.exit(1)});
